# Generated by Django 3.2.4 on 2022-02-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20220220_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(default='1000'),
            preserve_default=False,
        ),
    ]
