# Generated by Django 3.2.4 on 2022-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Instructor', 'Instructor'), ('Instructor', 'Student'), ('Instructor', 'Admin')], max_length=20),
        ),
    ]
