# Generated by Django 3.2.4 on 2022-03-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220228_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('student', 'Student'), ('admin', 'Admin')], max_length=20),
        ),
    ]
