# Generated by Django 3.2.4 on 2022-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('instructor', 'Instructor'), ('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
